Update dependencies
braintree/extended-promise pull request #16
Opened 2023-08-22 21:01 UTC by ibooker

Update dependencies

-   Update node to v18
-   Update to latest version of TypeScript
-   Update to latest version of prettier & eslint-plugin-prettier, ran prettier
-   Minor updates for other dependencies

For internal tracking -> 2919

2023-08-24 00:52 UTC, oscarleonnogales commented on CHANGELOG.md
> +# UNRELEASED
Nit: Missing a blank line

2023-08-24 00:52 UTC, oscarleonnogales approved these changes

2023-08-28 18:01 UTC, jplukarski requested changes
Need to also update the node version using in the CI workflow

2023-08-28 18:01 UTC, jplukarski commented on CHANGELOG.md
> +- Dependency Updates
Separate by `DevDependencies` and `Dependencies.

2023-08-29 17:32 UTC, ibooker commented
> Need to also update the node version using in the CI workflow

Had to create a [separate PR](https://github.com/braintree/extended-promise/pull/17) to update the workflow.

2023-08-30 21:29 UTC, jplukarski approved these changes

2023-08-30 21:38 UTC, merged